# +--------------------+
# Permissive Pod Security Policy (psp)
# +--------------------+

# (When psps aren't used, this is what is allowed in Kubernetes)
# Helps us understand the syntax
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies

#---
#apiVersion: policy/v1beta1
#kind: PodSecurityPolicy
#metadata:
#  name: default
#  annotations:
#    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
#spec:
#  privileged: true
#  allowPrivilegeEscalation: true
#  allowedCapabilities:
#  - '*'
#  volumes:
#  - '*'
#  hostNetwork: true
#  hostPorts:
#  - min: 0
#    max: 65535
#  hostIPC: true
#  hostPID: true
#  runAsUser:
#    rule: 'RunAsAny'
#  seLinux:
#    rule: 'RunAsAny'
#  supplementalGroups:
#    rule: 'RunAsAny'
#  fsGroup:
#    rule: 'RunAsAny'
#---

# +--------------------+
# AUTH POLICIES
# +--------------------+

# Auth policies that allow psps to execute

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:default
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:default
roleRef:
  kind: ClusterRole
  name: psp:default
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
---

# +--------------------+
# PSP
# +--------------------+

# Generated via:
# kubectl advise-psp inspect --namespace default

# Outputs a Pod Security Policy that allows our CURRENT infrastructure to run
# Note the allowedHostPaths and the hostPath volume (this allowed the docker credentials to be exfiltrated)

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default
spec:
  allowedHostPaths:
  - pathPrefix: /
    readOnly: true
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 0
    min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret

